#include <avr/io.h>
#include <util/delay.h>
#include "gpio.h"


void 
gpio_init(void)
{
	PORTA_DIR = 0;

	PORTB_OUT = 0x00;
	PORTB_DIR = IPMC_IN0_DIR | IPMC_IN1_DIR | IPMC_OUT0_DIR | BD_POWER_OFF_DIR;

	//PORTE_OUT = 0x00;
	PORTE_DIR = IPMC_READY_A_DIR | IPMC_FAULT_A_DIR | 0x02;

	//PORTF_OUT = 0x00;
	PORTF_DIR = IPMC_READY_B_DIR | IPMC_FAULT_B_DIR | 0x02;

	PORTH_DIR = HA_DIR;

	PORTJ_OUT = 0;
	PORTJ_OUT |= GPIO_LED_2_FAIL | GPIO_LED_3_STBY;
	PORTJ_DIR = N48V_ALARM_DIR | ATC250_CNTL1_DIR | ATC250_CNTL2_DIR | ATC250_CNTL3_DIR | \
				GPIO_PW_12V_D_DIR | GPIO_PW_12V_CP_DIR | GPIO_LED_2_FAIL_DIR | GPIO_LED_3_STBY_DIR;

	PORTK_OUT = GPIO_FRU_LED_1| GPIO_FRU_LED_2| GPIO_FRU_LED_3 | GPIO_FRU_LED_BLUE | IPMC_RESTART | IPMC_BD_RESET;
	PORTK_DIR = GPIO_LED_1_DIR| GPIO_LED_2_DIR| GPIO_LED_3_DIR| GPIO_LED_BLUE_DIR | \
				HANDLE_SW_DIR | IPMC_RESTART_DIR | IPMC_BD_RESET_DIR;

	PMIC_CTRL |= PMIC_MEDLVLEX_bm;
}
